#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <num1> <num2> <num3>"
    exit 1
fi

num1=$1
num2=$2
num3=$3

max=$num1

if [ "$num2" -gt "$largest" ]; then
    max=$num2
fi

if [ "$num3" -gt "$largest" ]; then
    max=$num3
fi

echo "The largest number is: $max
"
