#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Enter TIME EX: 1600"
    exit 1
fi

hour=$1

if (( hour >= 0 && hour < 12 )); then
    echo "Good Morning"
elif (( hour >= 12 && hour < 18 )); then
    echo "Good Afternoon"
else
    echo "Good Evening"
fi
